---
# This file must be signed. You can do so with the `mage drone` command

kind: pipeline
type: docker
name:

platform:
  os: linux
  arch: amd64

steps:
  - name: initialize
    image: grafana/grafana-plugin-ci:1.9.5
    commands:
      - . ~/.init-nvm.sh
      - mkdir -p bin
      - curl -fL -o bin/grabpl https://grafana-downloads.storage.googleapis.com/grafana-build-pipeline/v0.5.27/grabpl
      - chmod +x bin/grabpl
      - mkdir ci
      - yarn install --frozen-lockfile --no-progress
      - rm -rf node_modules/@grafana/data/node_modules
  - name: spellcheck
    image: grafana/grafana-plugin-ci:1.9.5
    commands:
      - . ~/.init-nvm.sh
      - yarn run spellcheck
    depends_on:
      - initialize
  - name: build-and-test-frontend
    image: grafana/grafana-plugin-ci:1.9.5
    commands:
      - . ~/.init-nvm.sh
      - yarn eslint ./src --ext .js,.jsx,.ts,.tsx
      - yarn build
      - yarn test:ci
    depends_on:
      - initialize
      - spellcheck

---
kind: signature
hmac: e3f399d799348ebebae40890fd1bf5845b884579354ca2e5d37e2851440dbf06

...
