checksumBehavior: throw

defaultSemverRangePrefix: ""

enableHardenedMode: true

enableImmutableInstalls: true

enableScripts: false

nmHoistingLimits: workspaces

nodeLinker: node-modules

npmMinimalAgeGate: 4320

unsafeHttpWhitelist: []

# Bypass minimal age gate for specific grafana packages to make feature development easier.
npmPreapprovedPackages:
  - "@grafana/*"

npmRegistryServer: "https://registry.npmjs.org"

yarnPath: .yarn/releases/yarn-4.15.0.cjs
